import { DEMO_USER_ID } from "@/lib/demo-mode";
import type {
  PlaceholderPerson,
  Relationship,
  RelationshipType,
  User,
} from "@/types/models";

const now = new Date("2026-05-23T12:00:00.000Z").toISOString();

export const demoUsers: User[] = [
  {
    id: DEMO_USER_ID,
    name: "Sydney Wells",
    firstName: "Sydney",
    lastName: "Wells",
    handle: "sydney.demo",
    pronouns: "She/Her",
    bio: "Mapping a consent-first private network for review.",
    interests: ["community", "events", "relationship maps"],
    relationshipStatus: "connected",
    location: "New York City, NY",
    links: { website: "https://meshylinks.com" },
    featured: true,
    isPro: true,
    connectionScore: 64,
    totalConnections: 8,
    secondDegreeConnections: 21,
    profileImage: null,
  },
  {
    id: "demo-user-mara",
    name: "Mara Sol",
    firstName: "Mara",
    lastName: "Sol",
    handle: "mara.sol",
    pronouns: "She/They",
    bio: "Event producer and connector.",
    interests: ["music", "mutual aid"],
    relationshipStatus: "single",
    location: "Brooklyn, NY",
    links: {},
    featured: true,
    isPro: false,
    connectionScore: 48,
    totalConnections: 5,
    secondDegreeConnections: 16,
    profileImage: null,
  },
  {
    id: "demo-user-rey",
    name: "Rey Navarro",
    firstName: "Rey",
    lastName: "Navarro",
    handle: "rey.nav",
    pronouns: "They/Them",
    bio: "Writer, host, and friend-of-friends enthusiast.",
    interests: ["poetry", "dinners"],
    relationshipStatus: "it is complicated",
    location: "Austin, TX",
    links: {},
    featured: false,
    isPro: false,
    connectionScore: 39,
    totalConnections: 4,
    secondDegreeConnections: 11,
    profileImage: null,
  },
  {
    id: "demo-user-dani",
    name: "Dani Park",
    firstName: "Dani",
    lastName: "Park",
    handle: "danipark",
    pronouns: "Any/All",
    bio: "Always knows where everyone met.",
    interests: ["coffee", "design", "city walks"],
    relationshipStatus: "dating",
    location: "Los Angeles, CA",
    links: {},
    featured: false,
    isPro: false,
    connectionScore: 34,
    totalConnections: 4,
    secondDegreeConnections: 13,
    profileImage: null,
  },
  {
    id: "demo-user-lena",
    name: "Lena Ortiz",
    firstName: "Lena",
    lastName: "Ortiz",
    handle: "lena.o",
    pronouns: "She/Her",
    bio: "Community organizer.",
    interests: ["art", "organizing"],
    relationshipStatus: "single",
    location: "Miami, FL",
    links: {},
    featured: false,
    isPro: false,
    connectionScore: 29,
    totalConnections: 3,
    secondDegreeConnections: 10,
    profileImage: null,
  },
  {
    id: "demo-user-nico",
    name: "Nico Chen",
    firstName: "Nico",
    lastName: "Chen",
    handle: "nicochen",
    pronouns: "He/They",
    bio: "Keeps the group chat alive.",
    interests: ["food", "photos"],
    relationshipStatus: "single",
    location: "Seattle, WA",
    links: {},
    featured: false,
    isPro: false,
    connectionScore: 31,
    totalConnections: 3,
    secondDegreeConnections: 12,
    profileImage: null,
  },
];

function rel(
  id: string,
  source: string,
  target: string,
  type: RelationshipType,
): Relationship {
  return { id, source, target, type, note: "", isPublic: true, publicRequestedBy: null };
}

export const demoRelationships: Relationship[] = [
  rel("demo-rel-1", DEMO_USER_ID, "demo-user-mara", "Dating"),
  rel("demo-rel-2", DEMO_USER_ID, "demo-user-rey", "Talking"),
  rel("demo-rel-3", DEMO_USER_ID, "demo-user-dani", "FWB"),
  rel("demo-rel-4", "demo-user-mara", "demo-user-lena", "Situationship"),
  rel("demo-rel-5", "demo-user-rey", "demo-user-lena", "Exes"),
  rel("demo-rel-6", "demo-user-dani", "demo-user-nico", "complicated"),
  rel("demo-rel-7", "demo-user-nico", "demo-user-mara", "Lovers"),
];

export const demoPrivatePlaceholders: PlaceholderPerson[] = [
  {
    id: "demo-private-ivy",
    ownerId: DEMO_USER_ID,
    name: "Ivy Morgan",
    offerToNameMatch: true,
    email: "ivy@example.com",
    phoneNumber: "+15551234567",
    relationshipType: "Talking",
    note: "Met at Mara's rooftop dinner.",
    inviteToken: "demo-ivy-invite",
    linkedUserId: null,
    claimStatus: "invited",
    createdAt: now,
  },
  {
    id: "demo-private-cam",
    ownerId: DEMO_USER_ID,
    name: "Cam Rivera",
    offerToNameMatch: true,
    email: "",
    phoneNumber: "",
    relationshipType: "Exes",
    note: "Old connection, keep private for now.",
    inviteToken: null,
    linkedUserId: null,
    claimStatus: "unclaimed",
    createdAt: now,
  },
  {
    id: "demo-private-jules",
    ownerId: DEMO_USER_ID,
    name: "Jules Avery",
    offerToNameMatch: false,
    email: "jules@example.com",
    phoneNumber: "",
    relationshipType: "Situationship",
    note: "Needs confirmation before public chart.",
    inviteToken: null,
    linkedUserId: null,
    claimStatus: "unclaimed",
    createdAt: now,
  },
];

export const demoProfile = {
  name: "Sydney Wells",
  handle: "sydney.demo",
  pronouns: "She/Her",
  bio: "Mapping a consent-first private network for review.",
  location: "New York City, NY",
  relationshipStatus: "connected",
  interests: ["community", "events", "relationship maps"],
};
